{"_type": "school", "_id": "boston-university", "_score": 1962.3022, "_source": {"in_state_tuition_and_fees": 48436, "ownership": 1, "city": "Boston", "level": 2, "name": "Boston University", "acceptance_rate": 0.19, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 48436, "unit_id": 164988, "gpa_avg": 3.72}, "url": "https://www.collegeconfidential.com/schools/school/boston-university"}
{"_type": "school", "_id": "university-of-connecticut", "_score": 1666.8606, "_source": {"in_state_tuition_and_fees": 17226, "ownership": 2, "city": "Storrs", "level": 2, "name": "University of Connecticut", "acceptance_rate": 0.49, "state": "CT", "urbanization": 4, "out_state_tuition_and_fees": 39894, "unit_id": 129020, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/university-of-connecticut"}
{"_type": "school", "_id": "harvard-university", "_score": 1638.5613, "_source": {"in_state_tuition_and_fees": 45278, "ownership": 1, "city": "Cambridge", "level": 2, "name": "Harvard University", "acceptance_rate": 0.05, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 45278, "unit_id": 166027, "gpa_avg": 4.18}, "url": "https://www.collegeconfidential.com/schools/school/harvard-university"}
{"_type": "school", "_id": "suffolk-university", "_score": 1444.3167, "_source": {"in_state_tuition_and_fees": 33934, "ownership": 1, "city": "Boston", "level": 2, "name": "Suffolk University ", "acceptance_rate": 0.84, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 33934, "unit_id": 168005, "gpa_avg": 3.31}, "url": "https://www.collegeconfidential.com/schools/school/suffolk-university"}
{"_type": "school", "_id": "university-of-massachusetts-amherst", "_score": 1429.4504, "_source": {"in_state_tuition_and_fees": 16389, "ownership": 2, "city": "Amherst", "level": 2, "name": "University of Massachusetts Amherst", "acceptance_rate": 0.64, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 35710, "unit_id": 166629, "gpa_avg": 3.9}, "url": "https://www.collegeconfidential.com/schools/school/university-of-massachusetts-amherst"}
{"_type": "school", "_id": "university-of-new-hampshire", "_score": 1350.5526, "_source": {"in_state_tuition_and_fees": 18938, "ownership": 2, "city": "Durham", "level": 2, "name": "University of New Hampshire ", "acceptance_rate": 0.84, "state": "NH", "urbanization": 3, "out_state_tuition_and_fees": 36278, "unit_id": 183044, "gpa_avg": 3.52}, "url": "https://www.collegeconfidential.com/schools/school/university-of-new-hampshire"}
{"_type": "school", "_id": "tufts-university", "_score": 1349.3525, "_source": {"in_state_tuition_and_fees": 50604, "ownership": 1, "city": "Medford", "level": 2, "name": "Tufts University ", "acceptance_rate": 0.15, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 50604, "unit_id": 168148, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/tufts-university"}
{"_type": "school", "_id": "university-of-vermont", "_score": 1328.9698, "_source": {"in_state_tuition_and_fees": 19062, "ownership": 2, "city": "Burlington", "level": 2, "name": "University of Vermont", "acceptance_rate": 0.67, "state": "VT", "urbanization": 2, "out_state_tuition_and_fees": 43950, "unit_id": 231174, "gpa_avg": 3.66}, "url": "https://www.collegeconfidential.com/schools/school/university-of-vermont"}
{"_type": "school", "_id": "university-of-southern-maine", "_score": 1303.0706, "_source": {"in_state_tuition_and_fees": 9850, "ownership": 2, "city": "Portland", "level": 2, "name": "University of Southern Maine", "acceptance_rate": 0.81, "state": "ME", "urbanization": 1, "out_state_tuition_and_fees": 23590, "unit_id": 161554, "gpa_avg": 3.25}, "url": "https://www.collegeconfidential.com/schools/school/university-of-southern-maine"}
{"_type": "school", "_id": "yale-university", "_score": 1301.8706, "_source": {"in_state_tuition_and_fees": 47600, "ownership": 1, "city": "New Haven", "level": 2, "name": "Yale University", "acceptance_rate": 0.06, "state": "CT", "urbanization": 1, "out_state_tuition_and_fees": 47600, "unit_id": 130794, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/yale-university"}
{"_type": "school", "_id": "rhode-island-college", "_score": 1288.9209, "_source": {"in_state_tuition_and_fees": 8929, "ownership": 2, "city": "Providence", "level": 2, "name": "Rhode Island College", "acceptance_rate": 0.78, "state": "RI", "urbanization": 2, "out_state_tuition_and_fees": 21692, "unit_id": 217420, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/rhode-island-college"}
{"_type": "school", "_id": "university-of-maine", "_score": 1285.8043, "_source": {"in_state_tuition_and_fees": 11438, "ownership": 2, "city": "Orono", "level": 2, "name": "University of Maine", "acceptance_rate": 0.9, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 31748, "unit_id": 161253, "gpa_avg": 3.35}, "url": "https://www.collegeconfidential.com/schools/school/university-of-maine"}
{"_type": "school", "_id": "university-of-rhode-island", "_score": 1277.1713, "_source": {"in_state_tuition_and_fees": 14566, "ownership": 2, "city": "Kingston", "level": 2, "name": "University of Rhode Island", "acceptance_rate": 0.69, "state": "RI", "urbanization": 3, "out_state_tuition_and_fees": 31686, "unit_id": 217484, "gpa_avg": 3.53}, "url": "https://www.collegeconfidential.com/schools/school/university-of-rhode-island"}
{"_type": "school", "_id": "brown-university", "_score": 1275.9712, "_source": {"in_state_tuition_and_fees": 49346, "ownership": 1, "city": "Providence", "level": 2, "name": "Brown University", "acceptance_rate": 0.07, "state": "RI", "urbanization": 1, "out_state_tuition_and_fees": 49346, "unit_id": 217156, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/brown-university"}
{"_type": "school", "_id": "salem-state-university", "_score": 1237.1224, "_source": {"in_state_tuition_and_fees": 10884, "ownership": 2, "city": "Salem", "level": 2, "name": "Salem State University", "acceptance_rate": 0.86, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 17024, "unit_id": 167729, "gpa_avg": 3.17}, "url": "https://www.collegeconfidential.com/schools/school/salem-state-university"}
{"_type": "school", "_id": "bennington-college", "_score": 1237.1224, "_source": {"in_state_tuition_and_fees": 48220, "ownership": 1, "city": "Bennington", "level": 2, "name": "Bennington College", "acceptance_rate": 0.61, "state": "VT", "urbanization": 3, "out_state_tuition_and_fees": 48220, "unit_id": 230816, "gpa_avg": 3.49}, "url": "https://www.collegeconfidential.com/schools/school/bennington-college"}
{"_type": "school", "_id": "university-of-new-haven", "_score": 1225.3727, "_source": {"in_state_tuition_and_fees": 35650, "ownership": 1, "city": "West Haven", "level": 2, "name": "University of New Haven", "acceptance_rate": 0.83, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 35650, "unit_id": 129941, "gpa_avg": 3.46}, "url": "https://www.collegeconfidential.com/schools/school/university-of-new-haven"}
{"_type": "school", "_id": "boston-college", "_score": 1211.2231, "_source": {"in_state_tuition_and_fees": 49324, "ownership": 1, "city": "Chestnut Hill", "level": 2, "name": "Boston College", "acceptance_rate": 0.27, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 49324, "unit_id": 164924, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/boston-college"}
{"_type": "school", "_id": "university-of-massachusetts-lowell", "_score": 1204.99, "_source": {"in_state_tuition_and_fees": 15180, "ownership": 2, "city": "Lowell", "level": 2, "name": "University of Massachusetts Lowell", "acceptance_rate": 0.73, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 32827, "unit_id": 166513, "gpa_avg": 3.6}, "url": "https://www.collegeconfidential.com/schools/school/university-of-massachusetts-lowell"}
{"_type": "school", "_id": "central-connecticut-state-university", "_score": 1199.4734, "_source": {"in_state_tuition_and_fees": 11068, "ownership": 2, "city": "New Britain", "level": 2, "name": "Central Connecticut State University", "acceptance_rate": 0.66, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 22870, "unit_id": 128771, "gpa_avg": 3.15}, "url": "https://www.collegeconfidential.com/schools/school/central-connecticut-state-university"}
{"_type": "school", "_id": "simmons-university", "_score": 1185.3237, "_source": {"in_state_tuition_and_fees": 37380, "ownership": 1, "city": "Boston", "level": 2, "name": "Simmons University", "acceptance_rate": 0.73, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 37380, "unit_id": 167783, "gpa_avg": 3.86}, "url": "https://www.collegeconfidential.com/schools/school/simmons-university"}
{"_type": "school", "_id": "northeastern-university", "_score": 1181.0072, "_source": {"in_state_tuition_and_fees": 45530, "ownership": 1, "city": "Boston", "level": 2, "name": "Northeastern University", "acceptance_rate": 0.18, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 45530, "unit_id": 167358, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/northeastern-university"}
{"_type": "school", "_id": "university-of-hartford", "_score": 1177.8907, "_source": {"in_state_tuition_and_fees": 36460, "ownership": 1, "city": "West Hartford", "level": 2, "name": "University of Hartford ", "acceptance_rate": 0.76, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 36460, "unit_id": 129525, "gpa_avg": 3.34}, "url": "https://www.collegeconfidential.com/schools/school/university-of-hartford"}
{"_type": "school", "_id": "university-of-massachusetts-boston", "_score": 1170.4576, "_source": {"in_state_tuition_and_fees": 14613, "ownership": 2, "city": "Boston", "level": 2, "name": "University of Massachusetts Boston", "acceptance_rate": 0.76, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 35075, "unit_id": 166638, "gpa_avg": 3.38}, "url": "https://www.collegeconfidential.com/schools/school/university-of-massachusetts-boston"}
{"_type": "school", "_id": "plymouth-state-university", "_score": 1163.7411, "_source": {"in_state_tuition_and_fees": 14099, "ownership": 2, "city": "Plymouth", "level": 2, "name": "Plymouth State University", "acceptance_rate": 0.85, "state": "NH", "urbanization": 3, "out_state_tuition_and_fees": 22769, "unit_id": 183080, "gpa_avg": 2.96}, "url": "https://www.collegeconfidential.com/schools/school/plymouth-state-university"}
{"_type": "school", "_id": "quinnipiac-university", "_score": 1155.1079, "_source": {"in_state_tuition_and_fees": 42270, "ownership": 1, "city": "Hamden", "level": 2, "name": "Quinnipiac University", "acceptance_rate": 0.74, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 42270, "unit_id": 130226, "gpa_avg": 3.47}, "url": "https://www.collegeconfidential.com/schools/school/quinnipiac-university"}
{"_type": "school", "_id": "southern-new-hampshire-university", "_score": 1137.8418, "_source": {"in_state_tuition_and_fees": 30386, "ownership": 1, "city": "Manchester", "level": 2, "name": "Southern New Hampshire University", "acceptance_rate": 0.86, "state": "NH", "urbanization": 2, "out_state_tuition_and_fees": 30386, "unit_id": 183026, "gpa_avg": 3.18}, "url": "https://www.collegeconfidential.com/schools/school/southern-new-hampshire-university"}
{"_type": "school", "_id": "marlboro-college", "_score": 1133.5253, "_source": {"in_state_tuition_and_fees": 39250, "ownership": 1, "city": "Marlboro", "level": 2, "name": "Marlboro College", "acceptance_rate": 0.97, "state": "VT", "urbanization": 4, "out_state_tuition_and_fees": 39250, "unit_id": 230940, "gpa_avg": 3.09}, "url": "https://www.collegeconfidential.com/schools/school/marlboro-college"}
{"_type": "school", "_id": "roger-williams-university", "_score": 1124.8922, "_source": {"in_state_tuition_and_fees": 31800, "ownership": 1, "city": "Bristol", "level": 2, "name": "Roger Williams University", "acceptance_rate": 0.85, "state": "RI", "urbanization": 3, "out_state_tuition_and_fees": 31800, "unit_id": 217518, "gpa_avg": 3.49}, "url": "https://www.collegeconfidential.com/schools/school/roger-williams-university"}
{"_type": "school", "_id": "fairfield-university", "_score": 1120.5756, "_source": {"in_state_tuition_and_fees": 44875, "ownership": 1, "city": "Fairfield", "level": 2, "name": "Fairfield University", "acceptance_rate": 0.57, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 44875, "unit_id": 129242, "gpa_avg": 3.64}, "url": "https://www.collegeconfidential.com/schools/school/fairfield-university"}
{"_type": "school", "_id": "dartmouth-college", "_score": 1120.5756, "_source": {"in_state_tuition_and_fees": 49506, "ownership": 1, "city": "Hanover", "level": 2, "name": "Dartmouth College", "acceptance_rate": 0.08, "state": "NH", "urbanization": 3, "out_state_tuition_and_fees": 49506, "unit_id": 182670, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/dartmouth-college"}
{"_type": "school", "_id": "university-of-massachusetts-dartmouth", "_score": 1114.3425, "_source": {"in_state_tuition_and_fees": 14358, "ownership": 2, "city": "North Dartmouth", "level": 2, "name": "University of Massachusetts Dartmouth", "acceptance_rate": 0.75, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 30103, "unit_id": 167987, "gpa_avg": 3.29}, "url": "https://www.collegeconfidential.com/schools/school/university-of-massachusetts-dartmouth"}
{"_type": "school", "_id": "providence-college", "_score": 1111.9425, "_source": {"in_state_tuition_and_fees": 45400, "ownership": 1, "city": "Providence", "level": 2, "name": "Providence College", "acceptance_rate": 0.47, "state": "RI", "urbanization": 2, "out_state_tuition_and_fees": 45400, "unit_id": 217402, "gpa_avg": 3.48}, "url": "https://www.collegeconfidential.com/schools/school/providence-college"}
{"_type": "school", "_id": "keene-state-college", "_score": 1107.626, "_source": {"in_state_tuition_and_fees": 14568, "ownership": 2, "city": "Keene", "level": 2, "name": "Keene State College", "acceptance_rate": 0.81, "state": "NH", "urbanization": 3, "out_state_tuition_and_fees": 23756, "unit_id": 183062, "gpa_avg": 3}, "url": "https://www.collegeconfidential.com/schools/school/keene-state-college"}
{"_type": "school", "_id": "brandeis-university", "_score": 1090.3597, "_source": {"in_state_tuition_and_fees": 49598, "ownership": 1, "city": "Waltham", "level": 2, "name": "Brandeis University", "acceptance_rate": 0.3, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 49598, "unit_id": 165015, "gpa_avg": 3.84}, "url": "https://www.collegeconfidential.com/schools/school/brandeis-university"}
{"_type": "school", "_id": "fitchburg-state-university", "_score": 1090.3597, "_source": {"in_state_tuition_and_fees": 10505, "ownership": 2, "city": "Fitchburg", "level": 2, "name": "Fitchburg State University", "acceptance_rate": 0.88, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 16585, "unit_id": 165820, "gpa_avg": 3.04}, "url": "https://www.collegeconfidential.com/schools/school/fitchburg-state-university"}
{"_type": "school", "_id": "southern-connecticut-state-university", "_score": 1082.9266, "_source": {"in_state_tuition_and_fees": 10954, "ownership": 2, "city": "New Haven", "level": 2, "name": "Southern Connecticut State University", "acceptance_rate": 0.64, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 22194, "unit_id": 130493, "gpa_avg": 3}, "url": "https://www.collegeconfidential.com/schools/school/southern-connecticut-state-university"}
{"_type": "school", "_id": "bristol-community-college", "_score": 1064.4604, "_source": {"in_state_tuition_and_fees": 5664, "ownership": 2, "city": "Fall River", "level": 1, "name": "Bristol Community College ", "acceptance_rate": null, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 10608, "unit_id": 165033, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/bristol-community-college"}
{"_type": "school", "_id": "sacred-heart-university", "_score": 1042.8778, "_source": {"in_state_tuition_and_fees": 37170, "ownership": 1, "city": "Fairfield", "level": 2, "name": "Sacred Heart University", "acceptance_rate": 0.64, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 37170, "unit_id": 130253, "gpa_avg": 3.55}, "url": "https://www.collegeconfidential.com/schools/school/sacred-heart-university"}
{"_type": "school", "_id": "university-of-bridgeport", "_score": 1035.4446, "_source": {"in_state_tuition_and_fees": 30850, "ownership": 1, "city": "Bridgeport", "level": 2, "name": "University of Bridgeport", "acceptance_rate": 0.54, "state": "CT", "urbanization": 1, "out_state_tuition_and_fees": 30850, "unit_id": 128744, "gpa_avg": 3.04}, "url": "https://www.collegeconfidential.com/schools/school/university-of-bridgeport"}
{"_type": "school", "_id": "bridgewater-state-university", "_score": 1034.2446, "_source": {"in_state_tuition_and_fees": 10732, "ownership": 2, "city": "Bridgewater", "level": 2, "name": "Bridgewater State University", "acceptance_rate": 0.9, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 16872, "unit_id": 165024, "gpa_avg": 3.13}, "url": "https://www.collegeconfidential.com/schools/school/bridgewater-state-university"}
{"_type": "school", "_id": "western-new-england-university", "_score": 1034.2446, "_source": {"in_state_tuition_and_fees": 34030, "ownership": 1, "city": "Springfield", "level": 2, "name": "Western New England University", "acceptance_rate": 0.85, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 34030, "unit_id": 168254, "gpa_avg": 3.59}, "url": "https://www.collegeconfidential.com/schools/school/western-new-england-university"}
{"_type": "school", "_id": "worcester-polytechnic-institute", "_score": 1021.29504, "_source": {"in_state_tuition_and_fees": 45590, "ownership": 1, "city": "Worcester", "level": 2, "name": "Worcester Polytechnic Institute ", "acceptance_rate": 0.49, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 45590, "unit_id": 168421, "gpa_avg": 3.9}, "url": "https://www.collegeconfidential.com/schools/school/worcester-polytechnic-institute"}
{"_type": "school", "_id": "merrimack-college", "_score": 1018.1784, "_source": {"in_state_tuition_and_fees": 37670, "ownership": 1, "city": "North Andover", "level": 2, "name": "Merrimack College", "acceptance_rate": 0.82, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 37670, "unit_id": 166850, "gpa_avg": 3.2}, "url": "https://www.collegeconfidential.com/schools/school/merrimack-college"}
{"_type": "school", "_id": "champlain-college", "_score": 1016.97845, "_source": {"in_state_tuition_and_fees": 37536, "ownership": 1, "city": "Burlington", "level": 2, "name": "Champlain College", "acceptance_rate": 0.85, "state": "VT", "urbanization": 2, "out_state_tuition_and_fees": 37536, "unit_id": 230852, "gpa_avg": 3.4}, "url": "https://www.collegeconfidential.com/schools/school/champlain-college"}
{"_type": "school", "_id": "massachusetts-institute-of-technology", "_score": 1009.54535, "_source": {"in_state_tuition_and_fees": 46704, "ownership": 1, "city": "Cambridge", "level": 2, "name": "Massachusetts Institute of Technology", "acceptance_rate": 0.07, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 46704, "unit_id": 166683, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/massachusetts-institute-of-technology"}
{"_type": "school", "_id": "framingham-state-university", "_score": 1008.3454, "_source": {"in_state_tuition_and_fees": 11100, "ownership": 2, "city": "Framingham", "level": 2, "name": "Framingham State University", "acceptance_rate": 0.74, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 17180, "unit_id": 165866, "gpa_avg": 3.06}, "url": "https://www.collegeconfidential.com/schools/school/framingham-state-university"}
{"_type": "school", "_id": "castleton-university", "_score": 1008.3454, "_source": {"in_state_tuition_and_fees": 12544, "ownership": 2, "city": "Castleton", "level": 2, "name": "Castleton University", "acceptance_rate": 0.78, "state": "VT", "urbanization": 4, "out_state_tuition_and_fees": 28552, "unit_id": 230834, "gpa_avg": 3.02}, "url": "https://www.collegeconfidential.com/schools/school/castleton-university"}
{"_type": "school", "_id": "assumption-university", "_score": 1008.3454, "_source": {"in_state_tuition_and_fees": 36160, "ownership": 1, "city": "Worcester", "level": 2, "name": "Assumption University", "acceptance_rate": 0.81, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 36160, "unit_id": 164562, "gpa_avg": 3.37}, "url": "https://www.collegeconfidential.com/schools/school/assumption-university"}
{"_type": "school", "_id": "westfield-state-university", "_score": 1008.3454, "_source": {"in_state_tuition_and_fees": 10849, "ownership": 2, "city": "Westfield", "level": 2, "name": "Westfield State University", "acceptance_rate": 0.87, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 16929, "unit_id": 168263, "gpa_avg": 3.2}, "url": "https://www.collegeconfidential.com/schools/school/westfield-state-university"}
{"_type": "school", "_id": "worcester-state-university", "_score": 1008.3454, "_source": {"in_state_tuition_and_fees": 10161, "ownership": 2, "city": "Worcester", "level": 2, "name": "Worcester State University", "acceptance_rate": 0.81, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 16241, "unit_id": 168430, "gpa_avg": 3.37}, "url": "https://www.collegeconfidential.com/schools/school/worcester-state-university"}
{"_type": "school", "_id": "endicott-college", "_score": 999.7122, "_source": {"in_state_tuition_and_fees": 30492, "ownership": 1, "city": "Beverly", "level": 2, "name": "Endicott College", "acceptance_rate": 0.69, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 30492, "unit_id": 165699, "gpa_avg": 3.45}, "url": "https://www.collegeconfidential.com/schools/school/endicott-college"}
{"_type": "school", "_id": "wesleyan-university", "_score": 999.7122, "_source": {"in_state_tuition_and_fees": 49274, "ownership": 1, "city": "Middletown", "level": 2, "name": "Wesleyan University", "acceptance_rate": 0.16, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 49274, "unit_id": 130697, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/wesleyan-university"}
{"_type": "school", "_id": "western-connecticut-state-university", "_score": 996.5957, "_source": {"in_state_tuition_and_fees": 11781, "ownership": 2, "city": "Danbury", "level": 2, "name": "Western Connecticut State University", "acceptance_rate": 0.76, "state": "CT", "urbanization": 1, "out_state_tuition_and_fees": 24055, "unit_id": 130776, "gpa_avg": 3.38}, "url": "https://www.collegeconfidential.com/schools/school/western-connecticut-state-university"}
{"_type": "school", "_id": "springfield-technical-community-college", "_score": 995.3957, "_source": {"in_state_tuition_and_fees": 6606, "ownership": 2, "city": "Springfield", "level": 1, "name": "Springfield Technical Community College", "acceptance_rate": 0.81, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 13116, "unit_id": 167905, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/springfield-technical-community-college"}
{"_type": "school", "_id": "husson-university-bangor", "_score": 991.07916, "_source": {"in_state_tuition_and_fees": 16582, "ownership": 1, "city": "Bangor", "level": 2, "name": "Husson University", "acceptance_rate": 0.85, "state": "ME", "urbanization": 2, "out_state_tuition_and_fees": 16582, "unit_id": 487524, "gpa_avg": 3.28}, "url": "https://www.collegeconfidential.com/schools/school/husson-university-bangor"}
{"_type": "school", "_id": "salve-regina-university", "_score": 991.07916, "_source": {"in_state_tuition_and_fees": 36740, "ownership": 1, "city": "Newport", "level": 2, "name": "Salve Regina University ", "acceptance_rate": 0.74, "state": "RI", "urbanization": 2, "out_state_tuition_and_fees": 36740, "unit_id": 217536, "gpa_avg": 3.45}, "url": "https://www.collegeconfidential.com/schools/school/salve-regina-university"}
{"_type": "school", "_id": "franklin-pierce-university", "_score": 991.07916, "_source": {"in_state_tuition_and_fees": 33320, "ownership": 1, "city": "Rindge", "level": 2, "name": "Franklin Pierce University", "acceptance_rate": 0.78, "state": "NH", "urbanization": 4, "out_state_tuition_and_fees": 33320, "unit_id": 182795, "gpa_avg": 2.97}, "url": "https://www.collegeconfidential.com/schools/school/franklin-pierce-university"}
{"_type": "school", "_id": "mount-holyoke-college", "_score": 986.76263, "_source": {"in_state_tuition_and_fees": 43886, "ownership": 1, "city": "South Hadley", "level": 2, "name": "Mount Holyoke College", "acceptance_rate": 0.51, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 43886, "unit_id": 166939, "gpa_avg": 3.81}, "url": "https://www.collegeconfidential.com/schools/school/mount-holyoke-college"}
{"_type": "school", "_id": "middlebury-college", "_score": 982.44604, "_source": {"in_state_tuition_and_fees": 47828, "ownership": 1, "city": "Middlebury", "level": 2, "name": "Middlebury College", "acceptance_rate": 0.17, "state": "VT", "urbanization": 3, "out_state_tuition_and_fees": 47828, "unit_id": 230959, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/middlebury-college"}
{"_type": "school", "_id": "bard-college-at-simons-rock", "_score": 982.44604, "_source": {"in_state_tuition_and_fees": 50209, "ownership": 1, "city": "Great Barrington", "level": 2, "name": "Bard College at Simon's Rock", "acceptance_rate": 0.84, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 50209, "unit_id": 167792, "gpa_avg": 3.54}, "url": "https://www.collegeconfidential.com/schools/school/bard-college-at-simons-rock"}
{"_type": "school", "_id": "community-college-of-rhode-island", "_score": 982.44604, "_source": {"in_state_tuition_and_fees": 4564, "ownership": 2, "city": "Warwick", "level": 1, "name": "Community College of Rhode Island ", "acceptance_rate": 0.99, "state": "RI", "urbanization": 1, "out_state_tuition_and_fees": 12156, "unit_id": 217475, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/community-college-of-rhode-island"}
{"_type": "school", "_id": "springfield-college", "_score": 982.44604, "_source": {"in_state_tuition_and_fees": 34455, "ownership": 1, "city": "Springfield", "level": 2, "name": "Springfield College", "acceptance_rate": 1.31, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 34455, "unit_id": 167899, "gpa_avg": 3.41}, "url": "https://www.collegeconfidential.com/schools/school/springfield-college"}
{"_type": "school", "_id": "clark-university", "_score": 973.813, "_source": {"in_state_tuition_and_fees": 41940, "ownership": 1, "city": "Worcester", "level": 2, "name": "Clark University ", "acceptance_rate": 0.59, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 41940, "unit_id": 165334, "gpa_avg": 3.67}, "url": "https://www.collegeconfidential.com/schools/school/clark-university"}
{"_type": "school", "_id": "trinity-college", "_score": 973.813, "_source": {"in_state_tuition_and_fees": 50776, "ownership": 1, "city": "Hartford", "level": 2, "name": "Trinity College ", "acceptance_rate": 0.34, "state": "CT", "urbanization": 1, "out_state_tuition_and_fees": 50776, "unit_id": 130590, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/trinity-college"}
{"_type": "school", "_id": "connecticut-college", "_score": 970.6965, "_source": {"in_state_tuition_and_fees": 49350, "ownership": 1, "city": "New London", "level": 2, "name": "Connecticut College", "acceptance_rate": 0.38, "state": "CT", "urbanization": 3, "out_state_tuition_and_fees": 49350, "unit_id": 128902, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/connecticut-college"}
{"_type": "school", "_id": "hampshire-college", "_score": 969.49646, "_source": {"in_state_tuition_and_fees": 49048, "ownership": 1, "city": "Amherst", "level": 2, "name": "Hampshire College ", "acceptance_rate": 0.02, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 49048, "unit_id": 166018, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/hampshire-college"}
{"_type": "school", "_id": "american-international-college", "_score": 969.49646, "_source": {"in_state_tuition_and_fees": 31870, "ownership": 1, "city": "Springfield", "level": 2, "name": "American International College", "acceptance_rate": 0.72, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 31870, "unit_id": 164447, "gpa_avg": 2.91}, "url": "https://www.collegeconfidential.com/schools/school/american-international-college"}
{"_type": "school", "_id": "wheaton-college", "_score": 965.1799, "_source": {"in_state_tuition_and_fees": 47700, "ownership": 1, "city": "Norton", "level": 2, "name": "Wheaton College", "acceptance_rate": 0.74, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 47700, "unit_id": 168281, "gpa_avg": 3.44}, "url": "https://www.collegeconfidential.com/schools/school/wheaton-college"}
{"_type": "school", "_id": "new-england-college", "_score": 965.1799, "_source": {"in_state_tuition_and_fees": 34606, "ownership": 1, "city": "Henniker", "level": 2, "name": "New England College", "acceptance_rate": 1, "state": "NH", "urbanization": 3, "out_state_tuition_and_fees": 34606, "unit_id": 182980, "gpa_avg": 2.63}, "url": "https://www.collegeconfidential.com/schools/school/new-england-college"}
{"_type": "school", "_id": "smith-college", "_score": 965.1799, "_source": {"in_state_tuition_and_fees": 46288, "ownership": 1, "city": "Northampton", "level": 2, "name": "Smith College", "acceptance_rate": 0.32, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 46288, "unit_id": 167835, "gpa_avg": 4}, "url": "https://www.collegeconfidential.com/schools/school/smith-college"}
{"_type": "school", "_id": "colby-college", "_score": 965.1799, "_source": {"in_state_tuition_and_fees": 49120, "ownership": 1, "city": "Waterville", "level": 2, "name": "Colby College", "acceptance_rate": 0.1, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 49120, "unit_id": 161086, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/colby-college"}
{"_type": "school", "_id": "bunker-hill-community-college", "_score": 960.86334, "_source": {"in_state_tuition_and_fees": 4704, "ownership": 2, "city": "Boston", "level": 1, "name": "Bunker Hill Community College", "acceptance_rate": 0.89, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 9648, "unit_id": 165112, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/bunker-hill-community-college"}
{"_type": "school", "_id": "stonehill-college", "_score": 960.86334, "_source": {"in_state_tuition_and_fees": 38550, "ownership": 1, "city": "Easton", "level": 2, "name": "Stonehill College", "acceptance_rate": 0.68, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 38550, "unit_id": 167996, "gpa_avg": 3.32}, "url": "https://www.collegeconfidential.com/schools/school/stonehill-college"}
{"_type": "school", "_id": "saint-michaels-college", "_score": 960.86334, "_source": {"in_state_tuition_and_fees": 40750, "ownership": 1, "city": "Colchester", "level": 2, "name": "Saint Michael's College", "acceptance_rate": 0.83, "state": "VT", "urbanization": 2, "out_state_tuition_and_fees": 40750, "unit_id": 231059, "gpa_avg": 3.4}, "url": "https://www.collegeconfidential.com/schools/school/saint-michaels-college"}
{"_type": "school", "_id": "anna-maria-college", "_score": 953.4303, "_source": {"in_state_tuition_and_fees": 35074, "ownership": 1, "city": "Paxton", "level": 2, "name": "Anna Maria College", "acceptance_rate": 0.79, "state": "MA", "urbanization": 4, "out_state_tuition_and_fees": 35074, "unit_id": 164492, "gpa_avg": 2.94}, "url": "https://www.collegeconfidential.com/schools/school/anna-maria-college"}
{"_type": "school", "_id": "university-of-saint-joseph", "_score": 953.4303, "_source": {"in_state_tuition_and_fees": 36200, "ownership": 1, "city": "West Hartford", "level": 2, "name": "University of Saint Joseph", "acceptance_rate": 0.77, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 36200, "unit_id": 130314, "gpa_avg": 3.44}, "url": "https://www.collegeconfidential.com/schools/school/university-of-saint-joseph"}
{"_type": "school", "_id": "wellesley-college", "_score": 952.2303, "_source": {"in_state_tuition_and_fees": 46836, "ownership": 1, "city": "Wellesley", "level": 2, "name": "Wellesley College", "acceptance_rate": 0.22, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 46836, "unit_id": 168218, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/wellesley-college"}
{"_type": "school", "_id": "gordon-college", "_score": 952.2303, "_source": {"in_state_tuition_and_fees": 35386, "ownership": 1, "city": "Wenham", "level": 2, "name": "Gordon College", "acceptance_rate": 0.74, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 35386, "unit_id": 165936, "gpa_avg": 3.58}, "url": "https://www.collegeconfidential.com/schools/school/gordon-college"}
{"_type": "school", "_id": "lesley-university", "_score": 947.9137, "_source": {"in_state_tuition_and_fees": 25095, "ownership": 1, "city": "Cambridge", "level": 2, "name": "Lesley University", "acceptance_rate": 0.75, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 25095, "unit_id": 166452, "gpa_avg": 3.31}, "url": "https://www.collegeconfidential.com/schools/school/lesley-university"}
{"_type": "school", "_id": "emmanuel-college", "_score": 944.7972, "_source": {"in_state_tuition_and_fees": 36504, "ownership": 1, "city": "Boston", "level": 2, "name": "Emmanuel College", "acceptance_rate": 0.78, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 36504, "unit_id": 165671, "gpa_avg": 3.74}, "url": "https://www.collegeconfidential.com/schools/school/emmanuel-college"}
{"_type": "school", "_id": "bentley-university", "_score": 943.59717, "_source": {"in_state_tuition_and_fees": 44085, "ownership": 1, "city": "Waltham", "level": 2, "name": "Bentley University", "acceptance_rate": 0.47, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 44085, "unit_id": 164739, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/bentley-university"}
{"_type": "school", "_id": "eastern-nazarene-college", "_score": 943.59717, "_source": {"in_state_tuition_and_fees": 29880, "ownership": 1, "city": "Quincy", "level": 2, "name": "Eastern Nazarene College", "acceptance_rate": 0.68, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 29880, "unit_id": 165644, "gpa_avg": 3}, "url": "https://www.collegeconfidential.com/schools/school/eastern-nazarene-college"}
{"_type": "school", "_id": "bowdoin-college", "_score": 939.28064, "_source": {"in_state_tuition_and_fees": 48212, "ownership": 1, "city": "Brunswick", "level": 2, "name": "Bowdoin College", "acceptance_rate": 0.09, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 48212, "unit_id": 161004, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/bowdoin-college"}
{"_type": "school", "_id": "cape-cod-community-college", "_score": 939.28064, "_source": {"in_state_tuition_and_fees": 4212, "ownership": 2, "city": "West Barnstable", "level": 1, "name": "Cape Cod Community College", "acceptance_rate": null, "state": "MA", "urbanization": 4, "out_state_tuition_and_fees": 9136, "unit_id": 165194, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/cape-cod-community-college"}
{"_type": "school", "_id": "university-of-new-england", "_score": 936.1641, "_source": {"in_state_tuition_and_fees": 34760, "ownership": 1, "city": "Biddeford", "level": 2, "name": "University of New England", "acceptance_rate": 0.84, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 34760, "unit_id": 161457, "gpa_avg": 3.35}, "url": "https://www.collegeconfidential.com/schools/school/university-of-new-england"}
{"_type": "school", "_id": "bryant-university", "_score": 934.9641, "_source": {"in_state_tuition_and_fees": 39808, "ownership": 1, "city": "Smithfield", "level": 2, "name": "Bryant University", "acceptance_rate": 0.71, "state": "RI", "urbanization": 2, "out_state_tuition_and_fees": 39808, "unit_id": 217165, "gpa_avg": 3.43}, "url": "https://www.collegeconfidential.com/schools/school/bryant-university"}
{"_type": "school", "_id": "northern-essex-community-college", "_score": 934.9641, "_source": {"in_state_tuition_and_fees": 5136, "ownership": 2, "city": "Haverhill", "level": 1, "name": "Northern Essex Community College", "acceptance_rate": 0.97, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 10920, "unit_id": 167376, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/northern-essex-community-college"}
{"_type": "school", "_id": "norwich-university", "_score": 930.6475, "_source": {"in_state_tuition_and_fees": 36092, "ownership": 1, "city": "Northfield", "level": 2, "name": "Norwich University", "acceptance_rate": 0.66, "state": "VT", "urbanization": 3, "out_state_tuition_and_fees": 36092, "unit_id": 230995, "gpa_avg": 3.07}, "url": "https://www.collegeconfidential.com/schools/school/norwich-university"}
{"_type": "school", "_id": "lasell-college", "_score": 930.6475, "_source": {"in_state_tuition_and_fees": 32000, "ownership": 1, "city": "Newton", "level": 2, "name": "Lasell College", "acceptance_rate": 0.84, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 32000, "unit_id": 166391, "gpa_avg": 3}, "url": "https://www.collegeconfidential.com/schools/school/lasell-college"}
{"_type": "school", "_id": "north-shore-community-college", "_score": 930.6475, "_source": {"in_state_tuition_and_fees": 5448, "ownership": 2, "city": "Danvers", "level": 1, "name": "North Shore Community College", "acceptance_rate": 0.92, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 11016, "unit_id": 167312, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/north-shore-community-college"}
{"_type": "school", "_id": "northern-vermont-university-johnson", "_score": 926.331, "_source": {"in_state_tuition_and_fees": 13204, "ownership": 2, "city": "Johnson", "level": 2, "name": "Northern Vermont University-Johnson", "acceptance_rate": 0.86, "state": "VT", "urbanization": 4, "out_state_tuition_and_fees": 26524, "unit_id": 230913, "gpa_avg": 3.32}, "url": "https://www.collegeconfidential.com/schools/school/northern-vermont-university-johnson"}
{"_type": "school", "_id": "williams-college", "_score": 926.331, "_source": {"in_state_tuition_and_fees": 50070, "ownership": 1, "city": "Williamstown", "level": 2, "name": "Williams College", "acceptance_rate": 0.13, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 50070, "unit_id": 168342, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/williams-college"}
{"_type": "school", "_id": "gateway-community-college", "_score": 926.331, "_source": {"in_state_tuition_and_fees": 4168, "ownership": 2, "city": "New Haven", "level": 1, "name": "Gateway Community College", "acceptance_rate": 0.97, "state": "CT", "urbanization": 1, "out_state_tuition_and_fees": 11608, "unit_id": 130396, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/gateway-community-college"}
{"_type": "school", "_id": "rivier-university", "_score": 922.01447, "_source": {"in_state_tuition_and_fees": 29700, "ownership": 1, "city": "Nashua", "level": 2, "name": "Rivier University", "acceptance_rate": 0.68, "state": "NH", "urbanization": 2, "out_state_tuition_and_fees": 29700, "unit_id": 183211, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/rivier-university"}
{"_type": "school", "_id": "naugatuck-valley-community-college", "_score": 922.01447, "_source": {"in_state_tuition_and_fees": 4696, "ownership": 2, "city": "Waterbury", "level": 1, "name": "Naugatuck Valley Community College", "acceptance_rate": 0.92, "state": "CT", "urbanization": 1, "out_state_tuition_and_fees": 13032, "unit_id": 129729, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/naugatuck-valley-community-college"}
{"_type": "school", "_id": "university-of-maine-at-farmington", "_score": 918.8979, "_source": {"in_state_tuition_and_fees": 9572, "ownership": 2, "city": "Farmington", "level": 2, "name": "University of Maine at Farmington", "acceptance_rate": 0.91, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 20282, "unit_id": 161226, "gpa_avg": 3.11}, "url": "https://www.collegeconfidential.com/schools/school/university-of-maine-at-farmington"}
{"_type": "school", "_id": "albertus-magnus-college", "_score": 917.69794, "_source": {"in_state_tuition_and_fees": 29650, "ownership": 1, "city": "New Haven", "level": 2, "name": "Albertus Magnus College", "acceptance_rate": 0.75, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 29650, "unit_id": 128498, "gpa_avg": 3.01}, "url": "https://www.collegeconfidential.com/schools/school/albertus-magnus-college"}
{"_type": "school", "_id": "eastern-connecticut-state-university", "_score": 914.5813, "_source": {"in_state_tuition_and_fees": 10919, "ownership": 2, "city": "Willimantic", "level": 2, "name": "Eastern Connecticut State University", "acceptance_rate": 0.64, "state": "CT", "urbanization": 3, "out_state_tuition_and_fees": 22377, "unit_id": 129215, "gpa_avg": 3.08}, "url": "https://www.collegeconfidential.com/schools/school/eastern-connecticut-state-university"}
{"_type": "school", "_id": "amherst-college", "_score": 913.3813, "_source": {"in_state_tuition_and_fees": 50562, "ownership": 1, "city": "Amherst", "level": 2, "name": "Amherst College", "acceptance_rate": 0.11, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 50562, "unit_id": 164465, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/amherst-college"}
{"_type": "school", "_id": "northern-vermont-university-lyndon", "_score": 904.7482, "_source": {"in_state_tuition_and_fees": 12434, "ownership": 2, "city": "Lyndonville", "level": 2, "name": "Northern Vermont University-Lyndon", "acceptance_rate": 0.93, "state": "VT", "urbanization": 4, "out_state_tuition_and_fees": 25754, "unit_id": 230931, "gpa_avg": 2.5}, "url": "https://www.collegeconfidential.com/schools/school/northern-vermont-university-lyndon"}
{"_type": "school", "_id": "quinsigamond-community-college", "_score": 904.7482, "_source": {"in_state_tuition_and_fees": 6870, "ownership": 2, "city": "Worcester", "level": 1, "name": "Quinsigamond Community College", "acceptance_rate": 0.67, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 13050, "unit_id": 167534, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/quinsigamond-community-college"}
{"_type": "school", "_id": "saint-anselm-college", "_score": 904.7482, "_source": {"in_state_tuition_and_fees": 37904, "ownership": 1, "city": "Manchester", "level": 2, "name": "Saint Anselm College ", "acceptance_rate": 0.75, "state": "NH", "urbanization": 2, "out_state_tuition_and_fees": 37904, "unit_id": 183239, "gpa_avg": 3.38}, "url": "https://www.collegeconfidential.com/schools/school/saint-anselm-college"}
{"_type": "school", "_id": "massachusetts-bay-community-college", "_score": 901.6317, "_source": {"in_state_tuition_and_fees": 5088, "ownership": 2, "city": "Wellesley Hills", "level": 1, "name": "Massachusetts Bay Community College", "acceptance_rate": 0.8, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 10032, "unit_id": 166647, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/massachusetts-bay-community-college"}
{"_type": "school", "_id": "emerson-college", "_score": 891.7986, "_source": {"in_state_tuition_and_fees": 41052, "ownership": 1, "city": "Boston", "level": 2, "name": "Emerson College", "acceptance_rate": 0.36, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 41052, "unit_id": 165662, "gpa_avg": 3.73}, "url": "https://www.collegeconfidential.com/schools/school/emerson-college"}
{"_type": "school", "_id": "johnson-and-wales-university-providence", "_score": 891.7986, "_source": {"in_state_tuition_and_fees": 29566, "ownership": 1, "city": "Providence", "level": 2, "name": "Johnson & Wales University", "acceptance_rate": 0.82, "state": "RI", "urbanization": 1, "out_state_tuition_and_fees": 29566, "unit_id": 217235, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/johnson-and-wales-university-providence"}
{"_type": "school", "_id": "mcphs-university", "_score": 891.7986, "_source": {"in_state_tuition_and_fees": 30530, "ownership": 1, "city": "Boston", "level": 2, "name": "MCPHS University", "acceptance_rate": 0.84, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 30530, "unit_id": 166656, "gpa_avg": 3.41}, "url": "https://www.collegeconfidential.com/schools/school/mcphs-university"}
{"_type": "school", "_id": "elms-college", "_score": 887.48206, "_source": {"in_state_tuition_and_fees": 32280, "ownership": 1, "city": "Chicopee", "level": 2, "name": "Elms College", "acceptance_rate": 0.75, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 32280, "unit_id": 167394, "gpa_avg": 3.48}, "url": "https://www.collegeconfidential.com/schools/school/elms-college"}
{"_type": "school", "_id": "becker-college", "_score": 883.1655, "_source": {"in_state_tuition_and_fees": 34080, "ownership": 1, "city": "Worcester", "level": 2, "name": "Becker College", "acceptance_rate": 0.7, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 34080, "unit_id": 164720, "gpa_avg": 3.18}, "url": "https://www.collegeconfidential.com/schools/school/becker-college"}
{"_type": "school", "_id": "manchester-community-college-manchester", "_score": 883.1655, "_source": {"in_state_tuition_and_fees": 4394, "ownership": 2, "city": "Manchester", "level": 1, "name": "Manchester Community College", "acceptance_rate": 1, "state": "CT", "urbanization": 3, "out_state_tuition_and_fees": 12218, "unit_id": 129695, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/manchester-community-college-manchester"}
{"_type": "school", "_id": "curry-college", "_score": 883.1655, "_source": {"in_state_tuition_and_fees": 36765, "ownership": 1, "city": "Milton", "level": 2, "name": "Curry College", "acceptance_rate": 0.93, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 36765, "unit_id": 165529, "gpa_avg": 2.97}, "url": "https://www.collegeconfidential.com/schools/school/curry-college"}
{"_type": "school", "_id": "bates-college", "_score": 878.84894, "_source": {"in_state_tuition_and_fees": 48435, "ownership": 1, "city": "Lewiston", "level": 2, "name": "Bates College", "acceptance_rate": 0.12, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 48435, "unit_id": 160977, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/bates-college"}
{"_type": "school", "_id": "post-university", "_score": 878.84894, "_source": {"in_state_tuition_and_fees": 16510, "ownership": 1, "city": "Waterbury", "level": 2, "name": "Post University", "acceptance_rate": 0.63, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 16510, "unit_id": 130183, "gpa_avg": 2.68}, "url": "https://www.collegeconfidential.com/schools/school/post-university"}
{"_type": "school", "_id": "mount-wachusett-community-college", "_score": 878.84894, "_source": {"in_state_tuition_and_fees": 5668, "ownership": 2, "city": "Gardner", "level": 1, "name": "Mount Wachusett Community College", "acceptance_rate": 0.99, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 10588, "unit_id": 166957, "gpa_avg": 2.5}, "url": "https://www.collegeconfidential.com/schools/school/mount-wachusett-community-college"}
{"_type": "school", "_id": "vermont-technical-college", "_score": 870.2159, "_source": {"in_state_tuition_and_fees": 16471, "ownership": 2, "city": "Randolph Center", "level": 2, "name": "Vermont Technical College", "acceptance_rate": 0.68, "state": "VT", "urbanization": 4, "out_state_tuition_and_fees": 29887, "unit_id": 231165, "gpa_avg": 3.11}, "url": "https://www.collegeconfidential.com/schools/school/vermont-technical-college"}
{"_type": "school", "_id": "three-rivers-community-college", "_score": 870.2159, "_source": {"in_state_tuition_and_fees": 4936, "ownership": 2, "city": "Norwich", "level": 1, "name": "Three Rivers Community College", "acceptance_rate": null, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 13704, "unit_id": 129808, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/three-rivers-community-college"}
{"_type": "school", "_id": "norwalk-community-college", "_score": 865.89935, "_source": {"in_state_tuition_and_fees": 4188, "ownership": 2, "city": "Norwalk", "level": 1, "name": "Norwalk Community College", "acceptance_rate": null, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 11628, "unit_id": 130004, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/norwalk-community-college"}
{"_type": "school", "_id": "bay-path-university", "_score": 861.58276, "_source": {"in_state_tuition_and_fees": 31785, "ownership": 1, "city": "Longmeadow", "level": 2, "name": "Bay Path University", "acceptance_rate": 0.63, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 31785, "unit_id": 164632, "gpa_avg": 3.4}, "url": "https://www.collegeconfidential.com/schools/school/bay-path-university"}
{"_type": "school", "_id": "saint-josephs-college-of-maine", "_score": 861.58276, "_source": {"in_state_tuition_and_fees": 32620, "ownership": 1, "city": "Standish", "level": 2, "name": "Saint Joseph's College of Maine", "acceptance_rate": 0.88, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 32620, "unit_id": 161518, "gpa_avg": 3}, "url": "https://www.collegeconfidential.com/schools/school/saint-josephs-college-of-maine"}
{"_type": "school", "_id": "wentworth-institute-of-technology", "_score": 861.58276, "_source": {"in_state_tuition_and_fees": 32500, "ownership": 1, "city": "Boston", "level": 2, "name": "Wentworth Institute of Technology", "acceptance_rate": 0.69, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 32500, "unit_id": 168227, "gpa_avg": 3.11}, "url": "https://www.collegeconfidential.com/schools/school/wentworth-institute-of-technology"}
{"_type": "school", "_id": "regis-college", "_score": 857.26624, "_source": {"in_state_tuition_and_fees": 37540, "ownership": 1, "city": "Weston", "level": 2, "name": "Regis College", "acceptance_rate": 0.79, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 37540, "unit_id": 167598, "gpa_avg": 3.06}, "url": "https://www.collegeconfidential.com/schools/school/regis-college"}
{"_type": "school", "_id": "massasoit-community-college", "_score": 849.8332, "_source": {"in_state_tuition_and_fees": 5070, "ownership": 2, "city": "Brockton", "level": 1, "name": "Massasoit Community College", "acceptance_rate": null, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 10426, "unit_id": 166823, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/massasoit-community-college"}
{"_type": "school", "_id": "fisher-college", "_score": 848.6332, "_source": {"in_state_tuition_and_fees": 28942, "ownership": 1, "city": "Boston", "level": 2, "name": "Fisher College", "acceptance_rate": 0.69, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 28942, "unit_id": 165802, "gpa_avg": 2.57}, "url": "https://www.collegeconfidential.com/schools/school/fisher-college"}
{"_type": "school", "_id": "green-mountain-college", "_score": 844.3166, "_source": {"in_state_tuition_and_fees": 35340, "ownership": 1, "city": "Poultney", "level": 2, "name": "Green Mountain College", "acceptance_rate": 0.82, "state": "VT", "urbanization": 3, "out_state_tuition_and_fees": 35340, "unit_id": 230898, "gpa_avg": 3.12}, "url": "https://www.collegeconfidential.com/schools/school/green-mountain-college"}
{"_type": "school", "_id": "holyoke-community-college", "_score": 844.3166, "_source": {"in_state_tuition_and_fees": 5114, "ownership": 2, "city": "Holyoke", "level": 1, "name": "Holyoke Community College", "acceptance_rate": 0.87, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 10058, "unit_id": 166133, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/holyoke-community-college"}
{"_type": "school", "_id": "nichols-college", "_score": 840.00006, "_source": {"in_state_tuition_and_fees": 33300, "ownership": 1, "city": "Dudley", "level": 2, "name": "Nichols College", "acceptance_rate": 0.8, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 33300, "unit_id": 167260, "gpa_avg": 2.9}, "url": "https://www.collegeconfidential.com/schools/school/nichols-college"}
{"_type": "school", "_id": "colby-sawyer-college", "_score": 840.00006, "_source": {"in_state_tuition_and_fees": 38860, "ownership": 1, "city": "New London", "level": 2, "name": "Colby-Sawyer College", "acceptance_rate": 0.9, "state": "NH", "urbanization": 3, "out_state_tuition_and_fees": 38860, "unit_id": 182634, "gpa_avg": 3.3}, "url": "https://www.collegeconfidential.com/schools/school/colby-sawyer-college"}
{"_type": "school", "_id": "southern-maine-community-college", "_score": 840.00006, "_source": {"in_state_tuition_and_fees": 3820, "ownership": 2, "city": "South Portland", "level": 1, "name": "Southern Maine Community College", "acceptance_rate": null, "state": "ME", "urbanization": 2, "out_state_tuition_and_fees": 6640, "unit_id": 161545, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/southern-maine-community-college"}
{"_type": "school", "_id": "college-of-the-holy-cross", "_score": 835.68353, "_source": {"in_state_tuition_and_fees": 47176, "ownership": 1, "city": "Worcester", "level": 2, "name": "College of the Holy Cross ", "acceptance_rate": 0.34, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 47176, "unit_id": 166124, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/college-of-the-holy-cross"}
{"_type": "school", "_id": "unity-college", "_score": 835.68353, "_source": {"in_state_tuition_and_fees": 26800, "ownership": 1, "city": "Unity", "level": 2, "name": "Unity College", "acceptance_rate": 0.89, "state": "ME", "urbanization": 4, "out_state_tuition_and_fees": 26800, "unit_id": 161572, "gpa_avg": 3.3}, "url": "https://www.collegeconfidential.com/schools/school/unity-college"}
{"_type": "school", "_id": "middlesex-community-college", "_score": 831.3669, "_source": {"in_state_tuition_and_fees": 6110, "ownership": 2, "city": "Bedford", "level": 1, "name": "Middlesex Community College", "acceptance_rate": null, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 12062, "unit_id": 166887, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/middlesex-community-college"}
{"_type": "school", "_id": "wheelock-college", "_score": 831.3669, "_source": {"in_state_tuition_and_fees": 33835, "ownership": 1, "city": "Boston", "level": 2, "name": "Wheelock College", "acceptance_rate": 0.84, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 33835, "unit_id": 168290, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/wheelock-college"}
{"_type": "school", "_id": "university-of-maine-at-presque-isle", "_score": 828.25037, "_source": {"in_state_tuition_and_fees": 8574, "ownership": 2, "city": "Presque Isle", "level": 2, "name": "University of Maine at Presque Isle", "acceptance_rate": 0.92, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 12984, "unit_id": 161341, "gpa_avg": 3}, "url": "https://www.collegeconfidential.com/schools/school/university-of-maine-at-presque-isle"}
{"_type": "school", "_id": "granite-state-college", "_score": 827.05035, "_source": {"in_state_tuition_and_fees": 7761, "ownership": 2, "city": "Concord", "level": 2, "name": "Granite State College", "acceptance_rate": 1, "state": "NH", "urbanization": 2, "out_state_tuition_and_fees": 8985, "unit_id": 183257, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/granite-state-college"}
{"_type": "school", "_id": "dean-college", "_score": 827.05035, "_source": {"in_state_tuition_and_fees": 35420, "ownership": 1, "city": "Franklin", "level": 2, "name": "Dean College", "acceptance_rate": 0.69, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 35420, "unit_id": 165574, "gpa_avg": 2.77}, "url": "https://www.collegeconfidential.com/schools/school/dean-college"}
{"_type": "school", "_id": "massachusetts-college-of-liberal-arts", "_score": 823.93384, "_source": {"in_state_tuition_and_fees": 10930, "ownership": 2, "city": "North Adams", "level": 2, "name": "Massachusetts College of Liberal Arts", "acceptance_rate": 0.74, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 19875, "unit_id": 167288, "gpa_avg": 3.2}, "url": "https://www.collegeconfidential.com/schools/school/massachusetts-college-of-liberal-arts"}
{"_type": "school", "_id": "massachusetts-college-of-art-and-design", "_score": 823.93384, "_source": {"in_state_tuition_and_fees": 11725, "ownership": 2, "city": "Boston", "level": 2, "name": "Massachusetts College of Art and Design", "acceptance_rate": 0.71, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 31225, "unit_id": 166674, "gpa_avg": 3.45}, "url": "https://www.collegeconfidential.com/schools/school/massachusetts-college-of-art-and-design"}
{"_type": "school", "_id": "university-of-maine-at-augusta", "_score": 823.93384, "_source": {"in_state_tuition_and_fees": 8168, "ownership": 2, "city": "Augusta", "level": 2, "name": "University of Maine at Augusta", "acceptance_rate": 0.98, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 18338, "unit_id": 161217, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/university-of-maine-at-augusta"}
{"_type": "school", "_id": "rhode-island-school-of-design", "_score": 822.7338, "_source": {"in_state_tuition_and_fees": 45840, "ownership": 1, "city": "Providence", "level": 2, "name": "Rhode Island School of Design ", "acceptance_rate": 0.26, "state": "RI", "urbanization": 1, "out_state_tuition_and_fees": 45840, "unit_id": 217493, "gpa_avg": 3.6}, "url": "https://www.collegeconfidential.com/schools/school/rhode-island-school-of-design"}
{"_type": "school", "_id": "nhti-concords-community-college", "_score": 819.6173, "_source": {"in_state_tuition_and_fees": 7104, "ownership": 2, "city": "Concord", "level": 1, "name": "NHTI, Concord's Community College", "acceptance_rate": null, "state": "NH", "urbanization": 3, "out_state_tuition_and_fees": 15264, "unit_id": 183099, "gpa_avg": 2.5}, "url": "https://www.collegeconfidential.com/schools/school/nhti-concords-community-college"}
{"_type": "school", "_id": "new-england-institute-of-technology", "_score": 818.4173, "_source": {"in_state_tuition_and_fees": 23031, "ownership": 1, "city": "East Greenwich", "level": 2, "name": "New England Institute of Technology", "acceptance_rate": null, "state": "RI", "urbanization": 2, "out_state_tuition_and_fees": 23031, "unit_id": 217305, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/new-england-institute-of-technology"}
{"_type": "school", "_id": "mount-ida-college", "_score": 818.4173, "_source": {"in_state_tuition_and_fees": 32300, "ownership": 1, "city": "Newton", "level": 2, "name": "Mount Ida College", "acceptance_rate": 0.63, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 32300, "unit_id": 166948, "gpa_avg": 2.6}, "url": "https://www.collegeconfidential.com/schools/school/mount-ida-college"}
{"_type": "school", "_id": "pine-manor-college", "_score": 815.3007, "_source": {"in_state_tuition_and_fees": 27050, "ownership": 1, "city": "Chestnut Hill", "level": 2, "name": "Pine Manor College", "acceptance_rate": 0.45, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 27050, "unit_id": 167455, "gpa_avg": 2.63}, "url": "https://www.collegeconfidential.com/schools/school/pine-manor-college"}
{"_type": "school", "_id": "housatonic-community-college", "_score": 809.7842, "_source": {"in_state_tuition_and_fees": 4504, "ownership": 2, "city": "Bridgeport", "level": 1, "name": "Housatonic Community College", "acceptance_rate": 1, "state": "CT", "urbanization": 1, "out_state_tuition_and_fees": 11252, "unit_id": 129543, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/housatonic-community-college"}
{"_type": "school", "_id": "capital-community-college", "_score": 809.7842, "_source": {"in_state_tuition_and_fees": 4102, "ownership": 2, "city": "Hartford", "level": 1, "name": "Capital Community College", "acceptance_rate": null, "state": "CT", "urbanization": 1, "out_state_tuition_and_fees": 12164, "unit_id": 129367, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/capital-community-college"}
{"_type": "school", "_id": "middlesex-community-college-middletown", "_score": 805.46765, "_source": {"in_state_tuition_and_fees": 4476, "ownership": 2, "city": "Middletown", "level": 1, "name": "Middlesex Community College", "acceptance_rate": 0.94, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 12444, "unit_id": 129756, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/middlesex-community-college-middletown"}
{"_type": "school", "_id": "college-of-st-joseph", "_score": 805.46765, "_source": {"in_state_tuition_and_fees": 21900, "ownership": 1, "city": "Rutland", "level": 2, "name": "College of St. Joseph", "acceptance_rate": 0.69, "state": "VT", "urbanization": 3, "out_state_tuition_and_fees": 21900, "unit_id": 231077, "gpa_avg": 2.8}, "url": "https://www.collegeconfidential.com/schools/school/college-of-st-joseph"}
{"_type": "school", "_id": "newbury-college", "_score": 805.46765, "_source": {"in_state_tuition_and_fees": 31408, "ownership": 1, "city": "Brookline", "level": 2, "name": "Newbury College", "acceptance_rate": 0.7, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 31408, "unit_id": 167251, "gpa_avg": 2.45}, "url": "https://www.collegeconfidential.com/schools/school/newbury-college"}
{"_type": "school", "_id": "kaplan-university-south-portland", "_score": 801.1511, "_source": {"in_state_tuition_and_fees": 11250, "ownership": 1, "city": "South Portland", "level": 1, "name": "Kaplan University, South Portland", "acceptance_rate": null, "state": "ME", "urbanization": 1, "out_state_tuition_and_fees": 11250, "unit_id": 160940, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/kaplan-university-south-portland"}
{"_type": "school", "_id": "thomas-college", "_score": 801.1511, "_source": {"in_state_tuition_and_fees": 24300, "ownership": 1, "city": "Waterville", "level": 2, "name": "Thomas College", "acceptance_rate": null, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 24300, "unit_id": 161563, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/thomas-college"}
{"_type": "school", "_id": "goodwin-college", "_score": 792.518, "_source": {"in_state_tuition_and_fees": 19950, "ownership": 1, "city": "East Hartford", "level": 1, "name": "Goodwin College", "acceptance_rate": null, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 19950, "unit_id": 129154, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/goodwin-college"}
{"_type": "school", "_id": "massachusetts-maritime-academy", "_score": 789.4015, "_source": {"in_state_tuition_and_fees": 10314, "ownership": 2, "city": "Buzzards Bay", "level": 2, "name": "Massachusetts Maritime Academy", "acceptance_rate": 0.91, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 25434, "unit_id": 166692, "gpa_avg": 3.14}, "url": "https://www.collegeconfidential.com/schools/school/massachusetts-maritime-academy"}
{"_type": "school", "_id": "tunxis-community-college", "_score": 788.2015, "_source": {"in_state_tuition_and_fees": 4464, "ownership": 2, "city": "Farmington", "level": 1, "name": "Tunxis Community College", "acceptance_rate": null, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 12288, "unit_id": 130606, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/tunxis-community-college"}
{"_type": "school", "_id": "purdue-university-global", "_score": 788.2015, "_source": {"in_state_tuition_and_fees": 11250, "ownership": 1, "city": "Augusta", "level": 2, "name": "Purdue University Global", "acceptance_rate": null, "state": "ME", "urbanization": 1, "out_state_tuition_and_fees": 11250, "unit_id": 480064, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/purdue-university-global"}
{"_type": "school", "_id": "university-of-maine-at-fort-kent", "_score": 785.08496, "_source": {"in_state_tuition_and_fees": 8115, "ownership": 2, "city": "Fort Kent", "level": 2, "name": "University of Maine at Fort Kent", "acceptance_rate": 0.99, "state": "ME", "urbanization": 4, "out_state_tuition_and_fees": 12315, "unit_id": 161235, "gpa_avg": 3.11}, "url": "https://www.collegeconfidential.com/schools/school/university-of-maine-at-fort-kent"}
{"_type": "school", "_id": "babson-college", "_score": 783.88495, "_source": {"in_state_tuition_and_fees": 46784, "ownership": 1, "city": "Babson Park", "level": 2, "name": "Babson College", "acceptance_rate": 0.26, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 46784, "unit_id": 164580, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/babson-college"}
{"_type": "school", "_id": "maine-maritime-academy", "_score": 776.45184, "_source": {"in_state_tuition_and_fees": 13078, "ownership": 2, "city": "Castine", "level": 2, "name": "Maine Maritime Academy", "acceptance_rate": 0.79, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 26158, "unit_id": 161299, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/maine-maritime-academy"}
{"_type": "school", "_id": "southern-vermont-college", "_score": 775.25183, "_source": {"in_state_tuition_and_fees": 23260, "ownership": 1, "city": "Bennington", "level": 2, "name": "Southern Vermont College", "acceptance_rate": 0.91, "state": "VT", "urbanization": 3, "out_state_tuition_and_fees": 23260, "unit_id": 231086, "gpa_avg": 2.35}, "url": "https://www.collegeconfidential.com/schools/school/southern-vermont-college"}
{"_type": "school", "_id": "university-of-new-hampshire-at-manchester", "_score": 767.8187, "_source": {"in_state_tuition_and_fees": 14860, "ownership": 2, "city": "Manchester", "level": 2, "name": "University of New Hampshire at Manchester", "acceptance_rate": 0.73, "state": "NH", "urbanization": 1, "out_state_tuition_and_fees": 29420, "unit_id": 183071, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/university-of-new-hampshire-at-manchester"}
{"_type": "school", "_id": "berkshire-community-college", "_score": 766.6188, "_source": {"in_state_tuition_and_fees": 10424, "ownership": 2, "city": "Pittsfield", "level": 1, "name": "Berkshire Community College", "acceptance_rate": 0.99, "state": "MA", "urbanization": 4, "out_state_tuition_and_fees": 21656, "unit_id": 164775, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/berkshire-community-college"}
{"_type": "school", "_id": "university-of-maine-at-machias", "_score": 763.50214, "_source": {"in_state_tuition_and_fees": 8036, "ownership": 2, "city": "Machias", "level": 2, "name": "University of Maine at Machias", "acceptance_rate": 0.99, "state": "ME", "urbanization": 4, "out_state_tuition_and_fees": 15116, "unit_id": 161244, "gpa_avg": 3.02}, "url": "https://www.collegeconfidential.com/schools/school/university-of-maine-at-machias"}
{"_type": "school", "_id": "asnuntuck-community-college", "_score": 762.3021, "_source": {"in_state_tuition_and_fees": 4032, "ownership": 2, "city": "Enfield", "level": 1, "name": "Asnuntuck Community College", "acceptance_rate": 1, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 11232, "unit_id": 128577, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/asnuntuck-community-college"}
{"_type": "school", "_id": "central-maine-community-college", "_score": 762.3021, "_source": {"in_state_tuition_and_fees": 3784, "ownership": 2, "city": "Auburn", "level": 1, "name": "Central Maine Community College", "acceptance_rate": 0.42, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 6604, "unit_id": 161077, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/central-maine-community-college"}
{"_type": "school", "_id": "northwestern-connecticut-community-college", "_score": 754.8691, "_source": {"in_state_tuition_and_fees": 4168, "ownership": 2, "city": "Winsted", "level": 1, "name": "Northwestern Connecticut Community College", "acceptance_rate": null, "state": "CT", "urbanization": 3, "out_state_tuition_and_fees": 11608, "unit_id": 130040, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/northwestern-connecticut-community-college"}
{"_type": "school", "_id": "greenfield-community-college", "_score": 753.66907, "_source": {"in_state_tuition_and_fees": 5570, "ownership": 2, "city": "Greenfield", "level": 1, "name": "Greenfield Community College", "acceptance_rate": null, "state": "MA", "urbanization": 3, "out_state_tuition_and_fees": 11690, "unit_id": 165981, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/greenfield-community-college"}
{"_type": "school", "_id": "lakes-region-community-college", "_score": 753.66907, "_source": {"in_state_tuition_and_fees": 6642, "ownership": 2, "city": "Laconia", "level": 1, "name": "Lakes Region Community College", "acceptance_rate": null, "state": "NH", "urbanization": 3, "out_state_tuition_and_fees": 14802, "unit_id": 183123, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/lakes-region-community-college"}
{"_type": "school", "_id": "white-mountains-community-college", "_score": 745.03595, "_source": {"in_state_tuition_and_fees": 7090, "ownership": 2, "city": "Berlin", "level": 1, "name": "White Mountains Community College", "acceptance_rate": 0.99, "state": "NH", "urbanization": 4, "out_state_tuition_and_fees": 15340, "unit_id": 183105, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/white-mountains-community-college"}
{"_type": "school", "_id": "college-of-the-atlantic", "_score": 745.03595, "_source": {"in_state_tuition_and_fees": 42084, "ownership": 1, "city": "Bar Harbor", "level": 2, "name": "College of the Atlantic", "acceptance_rate": 0.72, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 42084, "unit_id": 160959, "gpa_avg": 3.58}, "url": "https://www.collegeconfidential.com/schools/school/college-of-the-atlantic"}
{"_type": "school", "_id": "quincy-college", "_score": 740.7194, "_source": {"in_state_tuition_and_fees": 5524, "ownership": 2, "city": "Quincy", "level": 1, "name": "Quincy College", "acceptance_rate": null, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 5524, "unit_id": 167525, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/quincy-college"}
{"_type": "school", "_id": "hellenic-college", "_score": 740.7194, "_source": {"in_state_tuition_and_fees": 22490, "ownership": 1, "city": "Brookline", "level": 2, "name": "Hellenic College", "acceptance_rate": 0.65, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 22490, "unit_id": 166054, "gpa_avg": 3.4}, "url": "https://www.collegeconfidential.com/schools/school/hellenic-college"}
{"_type": "school", "_id": "berklee-college-of-music", "_score": 740.7194, "_source": {"in_state_tuition_and_fees": 40082, "ownership": 1, "city": "Boston", "level": 2, "name": "Berklee College of Music", "acceptance_rate": 0.51, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 40082, "unit_id": 164748, "gpa_avg": 3}, "url": "https://www.collegeconfidential.com/schools/school/berklee-college-of-music"}
{"_type": "school", "_id": "new-england-conservatory-of-music", "_score": 740.7194, "_source": {"in_state_tuition_and_fees": 43055, "ownership": 1, "city": "Boston", "level": 2, "name": "New England Conservatory of Music", "acceptance_rate": 0.32, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 43055, "unit_id": 167057, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/new-england-conservatory-of-music"}
{"_type": "school", "_id": "northern-maine-community-college", "_score": 736.4029, "_source": {"in_state_tuition_and_fees": 3801, "ownership": 2, "city": "Presque Isle", "level": 1, "name": "Northern Maine Community College", "acceptance_rate": 0.55, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 6681, "unit_id": 161484, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/northern-maine-community-college"}
{"_type": "school", "_id": "mitchell-college", "_score": 732.08636, "_source": {"in_state_tuition_and_fees": 31000, "ownership": 1, "city": "New London", "level": 2, "name": "Mitchell College", "acceptance_rate": 0.74, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 31000, "unit_id": 129774, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/mitchell-college"}
{"_type": "school", "_id": "montserrat-college-of-art", "_score": 727.7698, "_source": {"in_state_tuition_and_fees": 29550, "ownership": 1, "city": "Beverly", "level": 2, "name": "Montserrat College of Art", "acceptance_rate": 0.79, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 29550, "unit_id": 166911, "gpa_avg": 2.93}, "url": "https://www.collegeconfidential.com/schools/school/montserrat-college-of-art"}
{"_type": "school", "_id": "kennebec-valley-community-college", "_score": 727.7698, "_source": {"in_state_tuition_and_fees": 3817, "ownership": 2, "city": "Fairfield", "level": 1, "name": "Kennebec Valley Community College", "acceptance_rate": null, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 6637, "unit_id": 161192, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/kennebec-valley-community-college"}
{"_type": "school", "_id": "eastern-maine-community-college", "_score": 723.45325, "_source": {"in_state_tuition_and_fees": 3462, "ownership": 2, "city": "Bangor", "level": 1, "name": "Eastern Maine Community College", "acceptance_rate": null, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 6282, "unit_id": 161138, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/eastern-maine-community-college"}
{"_type": "school", "_id": "franklin-w-olin-college-of-engineering", "_score": 719.1367, "_source": {"in_state_tuition_and_fees": 48181, "ownership": 1, "city": "Needham", "level": 2, "name": "Franklin W. Olin College of Engineering", "acceptance_rate": 0.16, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 48181, "unit_id": 441982, "gpa_avg": 3.9}, "url": "https://www.collegeconfidential.com/schools/school/franklin-w-olin-college-of-engineering"}
{"_type": "school", "_id": "great-bay-community-college", "_score": 719.1367, "_source": {"in_state_tuition_and_fees": 7104, "ownership": 2, "city": "Portsmouth", "level": 1, "name": "Great Bay Community College", "acceptance_rate": null, "state": "NH", "urbanization": 1, "out_state_tuition_and_fees": 15264, "unit_id": 183150, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/great-bay-community-college"}
{"_type": "school", "_id": "lincoln-college-of-new-england", "_score": 719.1367, "_source": {"in_state_tuition_and_fees": 19950, "ownership": 1, "city": "Southington", "level": 2, "name": "Lincoln College of New England", "acceptance_rate": 0.99, "state": "CT", "urbanization": 3, "out_state_tuition_and_fees": 19950, "unit_id": 128683, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/lincoln-college-of-new-england"}
{"_type": "school", "_id": "manchester-community-college", "_score": 714.8202, "_source": {"in_state_tuition_and_fees": 6880, "ownership": 2, "city": "Manchester", "level": 1, "name": "Manchester Community College", "acceptance_rate": null, "state": "NH", "urbanization": 1, "out_state_tuition_and_fees": 15040, "unit_id": 183132, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/manchester-community-college"}
{"_type": "school", "_id": "nashua-community-college", "_score": 714.8202, "_source": {"in_state_tuition_and_fees": 6912, "ownership": 2, "city": "Nashua", "level": 1, "name": "Nashua Community College", "acceptance_rate": null, "state": "NH", "urbanization": 1, "out_state_tuition_and_fees": 15072, "unit_id": 183141, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/nashua-community-college"}
{"_type": "school", "_id": "benjamin-franklin-institute-of-technology", "_score": 710.5036, "_source": {"in_state_tuition_and_fees": 16950, "ownership": 1, "city": "Boston", "level": 1, "name": "Benjamin Franklin Institute of Technology", "acceptance_rate": 0.71, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 16950, "unit_id": 165884, "gpa_avg": 2.32}, "url": "https://www.collegeconfidential.com/schools/school/benjamin-franklin-institute-of-technology"}
{"_type": "school", "_id": "cambridge-college", "_score": 706.1871, "_source": {"in_state_tuition_and_fees": 14004, "ownership": 1, "city": "Boston", "level": 2, "name": "Cambridge College", "acceptance_rate": 0.43, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 14004, "unit_id": 165167, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/cambridge-college"}
{"_type": "school", "_id": "river-valley-community-college", "_score": 697.554, "_source": {"in_state_tuition_and_fees": 7175, "ownership": 2, "city": "Claremont", "level": 1, "name": "River Valley Community College", "acceptance_rate": 0.77, "state": "NH", "urbanization": 4, "out_state_tuition_and_fees": 15751, "unit_id": 183114, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/river-valley-community-college"}
{"_type": "school", "_id": "quinebaug-valley-community-college", "_score": 697.554, "_source": {"in_state_tuition_and_fees": 4198, "ownership": 2, "city": "Danielson", "level": 1, "name": "Quinebaug Valley Community College", "acceptance_rate": 0.98, "state": "CT", "urbanization": 4, "out_state_tuition_and_fees": 11638, "unit_id": 130217, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/quinebaug-valley-community-college"}
{"_type": "school", "_id": "new-hampshire-institute-of-art", "_score": 693.2374, "_source": {"in_state_tuition_and_fees": 24690, "ownership": 1, "city": "Manchester", "level": 2, "name": "New Hampshire Institute of Art", "acceptance_rate": 0.58, "state": "NH", "urbanization": 1, "out_state_tuition_and_fees": 24690, "unit_id": 430810, "gpa_avg": 2.97}, "url": "https://www.collegeconfidential.com/schools/school/new-hampshire-institute-of-art"}
{"_type": "school", "_id": "goddard-college", "_score": 693.2374, "_source": {"in_state_tuition_and_fees": 15476, "ownership": 1, "city": "Plainfield", "level": 2, "name": "Goddard College", "acceptance_rate": 0.56, "state": "VT", "urbanization": 4, "out_state_tuition_and_fees": 15476, "unit_id": 230889, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/goddard-college"}
{"_type": "school", "_id": "landmark-college", "_score": 693.2374, "_source": {"in_state_tuition_and_fees": 51330, "ownership": 1, "city": "Putney", "level": 1, "name": "Landmark College", "acceptance_rate": 0.86, "state": "VT", "urbanization": 3, "out_state_tuition_and_fees": 51330, "unit_id": 247649, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/landmark-college"}
{"_type": "school", "_id": "york-county-community-college", "_score": 688.9209, "_source": {"in_state_tuition_and_fees": 3630, "ownership": 2, "city": "Wells", "level": 1, "name": "York County Community College", "acceptance_rate": 1, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": 6450, "unit_id": 420440, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/york-county-community-college"}
{"_type": "school", "_id": "roxbury-community-college", "_score": 688.9209, "_source": {"in_state_tuition_and_fees": 4414, "ownership": 2, "city": "Roxbury Crossing", "level": 1, "name": "Roxbury Community College", "acceptance_rate": 0.83, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 9718, "unit_id": 167631, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/roxbury-community-college"}
{"_type": "school", "_id": "community-college-of-vermont", "_score": 684.6044, "_source": {"in_state_tuition_and_fees": 8190, "ownership": 2, "city": "Montpelier", "level": 1, "name": "Community College of Vermont", "acceptance_rate": 0.59, "state": "VT", "urbanization": 4, "out_state_tuition_and_fees": 16230, "unit_id": 230861, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/community-college-of-vermont"}
{"_type": "school", "_id": "maine-college-of-art", "_score": 684.6044, "_source": {"in_state_tuition_and_fees": 32290, "ownership": 1, "city": "Portland", "level": 2, "name": "Maine College of Art", "acceptance_rate": null, "state": "ME", "urbanization": 1, "out_state_tuition_and_fees": 32290, "unit_id": 161509, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/maine-college-of-art"}
{"_type": "school", "_id": "washington-county-community-college", "_score": 671.65466, "_source": {"in_state_tuition_and_fees": 3722, "ownership": 2, "city": "Calais", "level": 1, "name": "Washington County Community College", "acceptance_rate": null, "state": "ME", "urbanization": 4, "out_state_tuition_and_fees": 6542, "unit_id": 161581, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/washington-county-community-college"}
{"_type": "school", "_id": "boston-architectural-college", "_score": 667.33813, "_source": {"in_state_tuition_and_fees": 20666, "ownership": 1, "city": "Boston", "level": 2, "name": "Boston Architectural College", "acceptance_rate": 0.15, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 20666, "unit_id": 164872, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/boston-architectural-college"}
{"_type": "school", "_id": "boston-baptist-college", "_score": 658.705, "_source": {"in_state_tuition_and_fees": 12600, "ownership": 1, "city": "Boston", "level": 2, "name": "Boston Baptist College", "acceptance_rate": null, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 12600, "unit_id": 164614, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/boston-baptist-college"}
{"_type": "school", "_id": "paier-college-of-art-inc", "_score": 654.3885, "_source": {"in_state_tuition_and_fees": 15450, "ownership": 1, "city": "Hamden", "level": 2, "name": "Paier College of Art, Inc.", "acceptance_rate": 0.7, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 15450, "unit_id": 130110, "gpa_avg": 3.4}, "url": "https://www.collegeconfidential.com/schools/school/paier-college-of-art-inc"}
{"_type": "school", "_id": "charter-oak-state-college", "_score": 654.3885, "_source": {"in_state_tuition_and_fees": 10243, "ownership": 2, "city": "New Britain", "level": 2, "name": "Charter Oak State College", "acceptance_rate": null, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 13243, "unit_id": 128780, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/charter-oak-state-college"}
{"_type": "school", "_id": "sterling-college", "_score": 654.3885, "_source": {"in_state_tuition_and_fees": 34890, "ownership": 1, "city": "Craftsbury Common", "level": 2, "name": "Sterling College", "acceptance_rate": null, "state": "VT", "urbanization": 4, "out_state_tuition_and_fees": 34890, "unit_id": 231095, "gpa_avg": 3.1}, "url": "https://www.collegeconfidential.com/schools/school/sterling-college"}
{"_type": "school", "_id": "thomas-more-college-of-liberal-arts", "_score": 654.3885, "_source": {"in_state_tuition_and_fees": 20400, "ownership": 1, "city": "Merrimack", "level": 2, "name": "Thomas More College of Liberal Arts", "acceptance_rate": 0.41, "state": "NH", "urbanization": 3, "out_state_tuition_and_fees": 20400, "unit_id": 183275, "gpa_avg": 3.33}, "url": "https://www.collegeconfidential.com/schools/school/thomas-more-college-of-liberal-arts"}
{"_type": "school", "_id": "st-vincents-college", "_score": 645.75543, "_source": {"in_state_tuition_and_fees": 14630, "ownership": 1, "city": "Bridgeport", "level": 1, "name": "St. Vincent's College", "acceptance_rate": null, "state": "CT", "urbanization": 1, "out_state_tuition_and_fees": 14630, "unit_id": 130448, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/st-vincents-college"}
{"_type": "school", "_id": "bay-state-college", "_score": 619.85614, "_source": {"in_state_tuition_and_fees": 21524, "ownership": 1, "city": "Boston", "level": 1, "name": "Bay State College", "acceptance_rate": 0.53, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 21524, "unit_id": 164641, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/bay-state-college"}
{"_type": "school", "_id": "maine-college-of-health-professions", "_score": 619.85614, "_source": {"in_state_tuition_and_fees": 11400, "ownership": 1, "city": "Lewiston", "level": 1, "name": "Maine College of Health Professions", "acceptance_rate": 0.46, "state": "ME", "urbanization": 1, "out_state_tuition_and_fees": 11400, "unit_id": 161022, "gpa_avg": 3.63}, "url": "https://www.collegeconfidential.com/schools/school/maine-college-of-health-professions"}
{"_type": "school", "_id": "husson-university", "_score": 606.9065, "_source": {"in_state_tuition_and_fees": null, "ownership": 1, "city": "Bangor", "level": 2, "name": "Husson University", "acceptance_rate": 0.8, "state": "ME", "urbanization": 2, "out_state_tuition_and_fees": null, "unit_id": 161165, "gpa_avg": 3.3}, "url": "https://www.collegeconfidential.com/schools/school/husson-university"}
{"_type": "school", "_id": "beal-college", "_score": 589.6403, "_source": {"in_state_tuition_and_fees": null, "ownership": 1, "city": "Bangor", "level": 1, "name": "Beal College", "acceptance_rate": null, "state": "ME", "urbanization": 3, "out_state_tuition_and_fees": null, "unit_id": 160995, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/beal-college"}
{"_type": "school", "_id": "new-england-culinary-institute", "_score": 589.6403, "_source": {"in_state_tuition_and_fees": null, "ownership": 1, "city": "Montpelier", "level": 1, "name": "New England Culinary Institute", "acceptance_rate": null, "state": "VT", "urbanization": 3, "out_state_tuition_and_fees": null, "unit_id": 230977, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/new-england-culinary-institute"}
{"_type": "school", "_id": "holy-apostles-college-and-seminary", "_score": 581.0072, "_source": {"in_state_tuition_and_fees": 7750, "ownership": 1, "city": "Cromwell", "level": 2, "name": "Holy Apostles College and Seminary", "acceptance_rate": 1, "state": "CT", "urbanization": 2, "out_state_tuition_and_fees": 7750, "unit_id": 129534, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/holy-apostles-college-and-seminary"}
{"_type": "school", "_id": "labouri-college", "_score": 572.37415, "_source": {"in_state_tuition_and_fees": 34410, "ownership": 1, "city": "Milton", "level": 1, "name": "Labourï¿½ College", "acceptance_rate": null, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 34410, "unit_id": 165264, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/labouri-college"}
{"_type": "school", "_id": "the-landing-school", "_score": 568.05756, "_source": {"in_state_tuition_and_fees": 21694, "ownership": 1, "city": "Arundel", "level": 1, "name": "The Landing School", "acceptance_rate": 0.68, "state": "ME", "urbanization": 4, "out_state_tuition_and_fees": 21694, "unit_id": 161208, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/the-landing-school"}
{"_type": "school", "_id": "northpoint-bible-college", "_score": 559.4245, "_source": {"in_state_tuition_and_fees": 11150, "ownership": 1, "city": "Haverhill", "level": 2, "name": "Northpoint Bible College", "acceptance_rate": null, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 11150, "unit_id": 217606, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/northpoint-bible-college"}
{"_type": "school", "_id": "hult-international-business-school", "_score": 555.108, "_source": {"in_state_tuition_and_fees": 38850, "ownership": 1, "city": "Cambridge", "level": 2, "name": "Hult International Business School", "acceptance_rate": null, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 38850, "unit_id": 164368, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/hult-international-business-school"}
{"_type": "school", "_id": "new-england-college-of-business-and-finance", "_score": 546.47485, "_source": {"in_state_tuition_and_fees": 10525, "ownership": 1, "city": "Boston", "level": 2, "name": "New England College of Business and Finance", "acceptance_rate": null, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 10525, "unit_id": 164438, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/new-england-college-of-business-and-finance"}
{"_type": "school", "_id": "st-joseph-school-of-nursing", "_score": 546.47485, "_source": {"in_state_tuition_and_fees": 17272, "ownership": 1, "city": "Nashua", "level": 1, "name": "St. Joseph School of Nursing", "acceptance_rate": 0.4, "state": "NH", "urbanization": 1, "out_state_tuition_and_fees": 17272, "unit_id": 183248, "gpa_avg": 3.25}, "url": "https://www.collegeconfidential.com/schools/school/st-joseph-school-of-nursing"}
{"_type": "school", "_id": "magdalen-college-of-the-liberal-arts", "_score": 546.47485, "_source": {"in_state_tuition_and_fees": 21200, "ownership": 1, "city": "Warner", "level": 2, "name": "Magdalen College of the Liberal Arts", "acceptance_rate": null, "state": "NH", "urbanization": 3, "out_state_tuition_and_fees": 21200, "unit_id": 182917, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/magdalen-college-of-the-liberal-arts"}
{"_type": "school", "_id": "urban-college-of-boston", "_score": 511.94247, "_source": {"in_state_tuition_and_fees": 7124, "ownership": 1, "city": "Boston", "level": 1, "name": "Urban College of Boston", "acceptance_rate": null, "state": "MA", "urbanization": 1, "out_state_tuition_and_fees": 7124, "unit_id": 429128, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/urban-college-of-boston"}
{"_type": "school", "_id": "fine-mortuary-college-llc", "_score": 507.62592, "_source": {"in_state_tuition_and_fees": 19575, "ownership": 1, "city": "Norwood", "level": 1, "name": "FINE Mortuary College, LLC", "acceptance_rate": 0.86, "state": "MA", "urbanization": 2, "out_state_tuition_and_fees": 19575, "unit_id": 436599, "gpa_avg": null}, "url": "https://www.collegeconfidential.com/schools/school/fine-mortuary-college-llc"}
